version: '3'

services:
  taskredis:
    image: redis:4.0
    container_name: task-redis
    volumes:
      - redis-volume:/data
    ports:
      - "6379:6379"
  taskdb:
    image: mysql:8.0
    container_name: task-db
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
  taskmaster:
    image: jiangxianfu/taskflow:latest
    container_name: task-master
    environment:
      DOCKER_HOST: ${HOSTNAME}
    volumes:
      - .:/taskflow
      - taskmaster-volume:/var/log/taskflow
      - ./supervisord_master.conf:/etc/supervisord.conf
    command: ["supervisord"]
    depends_on:
      - taskredis
      - taskdb
    links:
      - taskredis
      - taskdb
  taskworker:
    image: jiangxianfu/taskflow:latest
    container_name: task-worker
    environment:
      DOCKER_HOST: ${HOSTNAME}
    volumes:
      - .:/taskflow
      - taskworker-volume:/var/log/taskflow
      - ./supervisord_worker.conf:/etc/supervisord.conf
    command: ["supervisord"]
    depends_on:
      - taskredis
      - taskdb
    links:
      - taskredis
      - taskdb
volumes:
  redis-volume:
  mysql-volume:
  taskmaster-volume:
  taskworker-volume:
